# Generated by Django 3.1.5 on 2021-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210111_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='endTown',
            field=models.CharField(choices=[('Ramenskoe', 'Раменское'), ('Kratovo', 'Кратово'), ('Zukovski', 'Жуковский'), ('Bronici', 'Бронницы'), ('Minino', 'Минино'), ('Ghel', 'Гжель'), ('Kosherovo', 'Кошерово'), ('Konyashino', 'Коняшино')], default='Ramenskoe', max_length=200, verbose_name='Конечный насел. пункт'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='startTown',
            field=models.CharField(choices=[('Ramenskoe', 'Раменское'), ('Kratovo', 'Кратово'), ('Zukovski', 'Жуковский'), ('Bronici', 'Бронницы'), ('Minino', 'Минино'), ('Ghel', 'Гжель'), ('Kosherovo', 'Кошерово'), ('Konyashino', 'Коняшино')], default='Ramenskoe', max_length=200, verbose_name='Начальный насел. пункт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Может вносить изменения в данные'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ в админ панель'),
        ),
    ]
