# Generated by Django 3.1.5 on 2021-01-12 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discountAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='promoCode',
            field=models.CharField(max_length=6, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='workExperience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Опыт работы (кол-во лет)'),
        ),
        migrations.AlterField(
            model_name='driverraiting',
            name='raiting',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка клиента'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='workExperience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Опыт работы (кол-во лет)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destinationTown',
            field=models.CharField(choices=[('Ramenskoe', 'Раменское'), ('Kratovo', 'Кратово'), ('Zukovski', 'Жуковский'), ('Bronici', 'Бронницы'), ('Minino', 'Минино'), ('Ghel', 'Гжель'), ('Kosherovo', 'Кошерово'), ('Konyashino', 'Коняшино')], default='Ramenskoe', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='town',
            field=models.CharField(choices=[('Ramenskoe', 'Раменское'), ('Kratovo', 'Кратово'), ('Zukovski', 'Жуковский'), ('Bronici', 'Бронницы'), ('Minino', 'Минино'), ('Ghel', 'Гжель'), ('Kosherovo', 'Кошерово'), ('Konyashino', 'Коняшино')], default='Ramenskoe', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(10000)], verbose_name='Цена'),
        ),
    ]
