# Generated by Django 3.1.5 on 2021-04-15 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210414_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullPrice', models.IntegerField(default=0, verbose_name='Общая стоимость услуги')),
                ('unauthorizedUser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Неавторизованный клиент')),
                ('appointmentStatus', models.CharField(choices=[('driver_waiting', 'сотрудник ожидает клиента'), ('client_canceled', 'клиент отменил запись'), ('in_progress', 'клиента обслуживают'), ('completed', 'выполнено')], default='driver_waiting', max_length=30, verbose_name='Статус записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время оформления')),
                ('scheduledTime', models.DateTimeField(blank=True, null=True, verbose_name='Назначенное время')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес проживания')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото сотрудника')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес проживания')),
                ('employeeStatus', models.CharField(choices=[('on_appointment', 'Принимает клиента'), ('waiting_appointment', 'В ожидании клиента'), ('on_sick_leave', 'На больничном'), ('on_vacation', 'В отпуске'), ('nonworking_time', 'Нерабочее время'), ('fired', 'Уволен')], default='nonworking_time', max_length=30, verbose_name='Статус сотрудника')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка товара')),
                ('countLeft', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во в наличии')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Тип товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка типа товаров')),
            ],
            options={
                'verbose_name': 'тип товаров',
                'verbose_name_plural': 'типы товаров',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullPrice', models.IntegerField(default=0, verbose_name='Общая стоимость услуги')),
                ('unauthorizedUser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Неавторизованный клиент')),
                ('purchaseStatus', models.CharField(choices=[('client_canceled', 'клиент отменил покупку'), ('in_progress', 'обработка'), ('completed', 'выполнена')], default='in_progress', max_length=30, verbose_name='Статус покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время оформления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client', verbose_name='Клиент')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discount', verbose_name='Скидка')),
                ('products', models.ManyToManyField(to='api.Product')),
            ],
            options={
                'verbose_name': 'покупка',
                'verbose_name_plural': 'покупки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка услуги')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость услуги')),
                ('percToEmpl', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент сотруднику')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание группы услуг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка группы')),
            ],
            options={
                'verbose_name': 'группа услуг',
                'verbose_name_plural': 'группы услуг',
            },
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуг')),
                ('workSchedule', models.CharField(choices=[('five_two', '5/2'), ('six_one', '6/1'), ('two_two', '2/2'), ('three_three', '3/3')], default='five_two', max_length=30, verbose_name='График работы')),
                ('serviceGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicegroup', verbose_name='Группа услуг')),
            ],
            options={
                'verbose_name': 'рабочее место',
                'verbose_name_plural': 'рабочие места',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverraiting',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverraiting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverraitingcomment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverraitingcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Клиент'), ('driver', 'Сторудник')], default='user', max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverRaiting',
        ),
        migrations.DeleteModel(
            name='DriverRaitingComment',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='service',
            name='serviceGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicegroup', verbose_name='Группа услуг'),
        ),
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producttype', verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workPosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workposition', verbose_name='Рабочее место'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='api.Service'),
        ),
    ]
